### PR TITLE
wasm

### PR DESCRIPTION
**Pull request by makc**
Yet another iteration on #151
Cleaned up bindings.cpp, added all three operations to 3js demo.

### CODE REVIEW

**Comment by makc** [comment]
@pca006132 build_nix is not green again, halp

**Comment by pca006132** [comment]
```
error: undefined symbol: __cxa_is_pointer_type (referenced by $CatchInfo__deps: ['$ExceptionInfo','__cxa_is_pointer_type'], referenced by __cxa_find_matching_catch_2__deps: ['$exceptionLast','$ExceptionInfo','$CatchInfo','__resumeException','__cxa_can_catch'], referenced by top-level compiled C/C++ code)
warning: ___cxa_is_pointer_type may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

ah interesting

**Comment by pca006132** [comment]
Related: https://github.com/emscripten-core/emscripten/issues/14313

I guess we somehow disabled linking exceptions in the build script?

**Comment by makc** [comment]
build_wasm is fine though. so you say this is because build_nix uses newer emscripten?

**Comment by pca006132** [comment]
Fix:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 27128dc..d7373fe 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,6 +9,7 @@ set(MANIFOLD_PAR "TBB" CACHE STRING "Parallel backend, either \"TBB\" or \"OpenM
 
 if(EMSCRIPTEN)
     message("Building for Emscripten")
+    set(MANIFOLD_FLAGS -fexceptions)
     set(CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} -sALLOW_MEMORY_GROWTH=1)
     set(MANIFOLD_USE_CUDA OFF)
     set(MANIFOLD_PAR "NONE")
```

**Comment by makc** [comment]
pure green

**Review by elalish — APPROVED** [review]
Excellent! Thanks for putting in the effort here, and the API looks great. As a follow-on, we should make sure to serve your index.html file on our Github pages so we can link it in our docs. That will make a compelling example to see live!

**Comment by makc** [comment]
@elalish btw, is there an example of using [this](https://github.com/elalish/manifold/wiki/Manifold-Library#vertex-properties) for applying uvs in c++ ?

**Comment by elalish** [comment]
Not really; the closest I have at the moment is [this](https://github.com/elalish/manifold/blob/master/test/mesh_test.cpp#L62-L85). The reason is that this is so dependent on your engine/format. Say you union two models with different textures. Do you atlas the images together and offset the UVs? Which way do you want to do that? What if the two models don't have the same texture channels? I give you all the math you need, but that's just the beginning. I think now that you've got a three.js example hooked up, this would be a good time to make a simple demo of atlasing textures. Or I suppose we could just attach copies of a single model so that they can all share the same texture - that's by far the simplest.

**Comment by makc** [comment]
to avoid changing uv layout, in the context of 3js there is an option to assign different materials to areas that used to belong to different operands. in another lib, the user could split the result into multiple meshes. I suppose I would need to step-by-step those tests to understand GetMeshIDs() and GetMeshRelation()

**Comment by elalish** [comment]
Yes, that's a good point, I forgot about their multiple material support. I believe it involves duplicating verts (pretty unavoidable in graphics) which makes it hard to come back to a manifold. However, my APIs contain all the info so we can apply the material stuff after all the operations have completed, so it should be fine. Would you like to start a PR? I'd be happy to help with the `MeshRelation` part.

**Pull request merged**
