### PR TITLE
Set up test for subtraction of a very large cuboid

### PR DESCRIPTION
**Pull request by starseeker**
Test case for #712 - these glb inputs were generated from manifolds that succeeded in producing a Boolean output, but (on one platform but not another) the Status() call on the output boolean manifold crashed.

(A test for calling Status() on the output captured on the crashing platform (in case there was something specifically bad about that particular output on that platform) was tried, but the result was simply a successful Status() call even with that specific input - hence, that additional test is not included in this commit.)

Right now we're using the same GetMeshGL() call as the other tests, but perhaps it would be preferable to use Status() instead since that was the observed failure?  I wasn't sure if the former was preferred as a more rigorous test of the Manifold structure.

### CODE REVIEW

**Comment by elalish** [comment]
Looks like we caught the problem here, thanks! I'll take a look.

**Comment by elalish** [comment]
I have a local repro of this problem - for once it's not the triangulator! @pca006132 Might be good to look at this case to get an idea of how to construct fuzzer tests. Speaking of, is there a way to use our fuzzer to minimize this test case?

**Comment by pca006132** [comment]
No, this is not something fuzzer can do. We can probably write something that simplifies the triangular mesh though.

**Comment by elalish** [comment]
Closing in favor of #714. Thanks for a good edge case test! For future reference, please make your PRs on a new branch - we can't merge if you're using master already.

**Pull request closed without merging**
