### PR TITLE
[python] fix warp callback

### PR DESCRIPTION
**Pull request by wrongbad**
I recently broke this making it a no-op due to the vec reference becoming a by-value copy in python callback. 

This fix provides a simple adapter like we had before allowing python to return modified values from the callback.

### CODE REVIEW

**Comment by elalish** [comment]
Can you add a test that shows the problem you're solving? Ideally using one of our warp sample models?

**Comment by wrongbad** [comment]
I updated torus_knot to expose both warp modes, so we can then test it in a ipynb like this:
```py
import sys
sys.path.append('bindings/python/examples')
import torus_knot
m = torus_knot.run(warp_single=True)

from badcad import Solid
Solid(m) # visualize in jupyter / vscode
```
Before:
Screen Shot 2023-12-26 at 6 34 12 PM
After:
Screen Shot 2023-12-26 at 6 35 21 PM

**Comment by wrongbad** [comment]
Did you want an automated regression test specifically? I guess we could check `len(m.split_by_plane().decompose())` as it would be different when the warp actually works.

**Comment by wrongbad** [comment]
I might need your help hooking up the CI side. I added those checks to a pytest setup. 

To run it, the scripts needs to pip install `manifold3d` package, and `pytest` package.
Then run `pytest` or `python -m pytest` from the `manifold` root.

Right now it will search python/examples for `test_*` files, and run all `test_*` functions, noting any assert failures.

**Comment by elalish** [comment]
I *think* you just need to add `pytest` [here](https://github.com/elalish/manifold/blob/master/.github/workflows/manifold.yml#L26).

**Review by elalish — APPROVED** [review]
Excellent, thank you! I appreciate the assertion pattern - we should definitely expand on that to match our JS testing.

**Pull request merged**
