### PR TITLE
Prepare a test input with failing boolean

### PR DESCRIPTION
**Pull request by starseeker**
Encountered this case when testing Manifold with the BRL-CAD example file - specifically, the r.glass8 region.  C++ exception "Vec out of range" is thrown.  Both inputs are the outputs of previous Manifold boolean evaluations.

### CODE REVIEW

**Comment by elalish** [comment]
Funny that both this one and #608 only fail on Linux TBB and Mac builds.

**Comment by pca006132** [comment]
maybe we did not enable MANIFOLD_EXPORT for the other CI?

**Comment by pca006132** [comment]
if you enable `MANIFOLD_DEBUG`, the triangulator throws an error:
```
Error in file: /home/pca006132/code/manifold/src/polygon/src/polygon.cpp (73): 'halfedges.size() % 2 == 0' is false: Odd number of halfedges.
```

I think we can merge this after changing the test name to disable it temporarily.

**Comment by starseeker** [comment]
Do you need me to make the name change?  If so, what name did you want?

**Comment by pca006132** [comment]
I can do it, give me a few minutes

**Review by elalish — APPROVED** [review]
Thanks, I'll debug.

**Pull request merged**
