### PR TITLE
Add CI check for formatting more languages

### PR DESCRIPTION
**Pull request by elalish**
Let's see if this works. FYI @geoffder.

### CODE REVIEW

**Comment by geoffder** [comment]
This will mean the CI complains, but without configs for the particular formatters we won't be coordinated to keep the checks happy will we? I'm not sure what it is that is being run for my formatting by the lsp, I think it's prettier for js. So I think we'd need a prettier config.

**Comment by elalish** [comment]
I'm using clang-format for everything, with `.clang-format` controlling it. Can you set up lsp that way?

**Comment by geoffder** [comment]
Oh, I wasn't aware clang-format did non C/C++ stuff. I'll look into swapping that in.

**Comment by geoffder** [comment]
I've got clang-format running now, but it looks like I'm going to have to wrestle with it a bit. It is splitting `=>` into `= >`, which needless to say, is not so good.

**Comment by geoffder** [comment]
Alright, well I never figured out why running clang-format through the usual formatter setup, but I went around it! Diffs are way down on the JS PR, so it seems like it is working as advertised.

**Pull request merged**
