### PR TITLE
fix various code documentation typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.pdf,./**/third_party -L boxs,inout,intstruct`

### CODE REVIEW

**Review by elalish — APPROVED** [review]
Thank you! I just installed a VSCode extension for spell-checking, but I clearly hadn't made it through all the files yet.

**Comment by elalish** [comment]
Let me know if you're having any trouble with the CLA.

**Comment by luzpaz** [comment]
@elalish I'd rather not sign the google CLA. i hereby give you full permission to take over this commit. Feel free to do with it what you will.

**Comment by elalish** [comment]
@luzpaz Alas! I tried to avoid the CLA requirement for exactly this reason. Would you mind telling me exactly how you feel about it? I'd like to be able to give the lawyers some accurate feedback.

**Comment by luzpaz** [comment]
Most CLAs are fine but this one requires a google account which feels super cringe

**Comment by elalish** [comment]
Fair point - honestly that sounds like laziness on the part of our bot engineers. I'll definitely give them that feedback, as I'm sorry to lose you as a potential contributor for such a procedural reason.

**Comment by luzpaz** [comment]
Thanks for inquiring. That's a redeeming quality for sure :wink:

**Comment by elalish** [comment]
Closing in favor of #270. Thanks for pointing this out.

**Pull request closed without merging**
