### PR TITLE
Add test case for wrong normals and uvs after boolean subtraction

### PR DESCRIPTION
**Pull request by jirihon**
Related to #579.

I know the test case is quite large, but I don't observe the problem for simpler geometry, at least for now.

The `RelatedGL` assertion fails here. I hope I used it correctly.

### CODE REVIEW

**Review by elalish — COMMENTED** [review]
Thank you, this is very helpful! Would you mind following this example [`TEST`](https://github.com/elalish/manifold/blob/master/test/samples_test.cpp#L258-L269) to load the model as a GLB instead?

**Comment by elalish** [comment]
Actually, making a GLB in this case is probably more trouble than it's worth. However, upon debugging your test, I found that roughly half of your normals for A are inverted. Can you fix that and update the test? I'm also curious if that will solve the problem anyway.

**Comment by jirihon** [comment]
Thanks for looking into this. The normals should be fixed now and the test is still failing.

**Comment by elalish** [comment]
closed in favor of #587. Thanks again for the test case!

**Pull request closed without merging**
