### PR TITLE
Multi-material example

### LINKED ISSUE #196: Build multi-material three.js example
I like the simplicity of @makc's first WASM [example](https://elalish.github.io/manifold/bindings/wasm/examples/index.html), so I plan to keep that (and add some explanation and link it from our readme). However, we could also use a more complex example to show how different objects with textures/materials can be combined into a [multi-material](https://github.com/elalish/manifold/pull/155#issuecomment-1186812460) result. 

I think as part of this I'll also integrate `<model-viewer>` as the viewer by exporting the three.js scene as a GLB blob. This work will also dovetail nicely with the other work going in to finishing #73.

### LINKED ISSUE #286: Imprecise barycentric coordinates
Barycentric coordinates in a MeshRelation object get warped after doing a boolean operation. I made a project that restores vertex attributes like UVs from a MeshRelation. If I do an operation that does nothing to the manifold (like translating by 0,0,0) and convert the manifold back to a mesh with restored vertex attributes, then the barycentric coordinates aren't warped:

original

However, if I do the same thing with an operation that modifies the manifold, then the barycentric coordinates are warped, resulting in UV artifacts:

bary-warped

This only happens for high UV values. In the screenshots, the U values are in the 0-1 range, but the V values are in the 18-19 range (due to repeating textures), suggesting that these issues are being created due to low precision

### PR DESCRIPTION
**Pull request by elalish**
Fixes #196 
Fixes #286 

This is a follow-on to #290 to demonstrate that the new property APIs work end-to-end by connecting them to glTF output. I've expanded `MeshGL` with a different style of `MeshRelation` data. I'm thinking I'll remove the old `MeshRelation` and `triProperties` input entirely now, basically saying `Mesh` is only for pure, simple geometry, while `MeshGL` is for anything requiring mesh properties and relationships.

### CODE REVIEW

**Comment by elalish** [comment]
Oops, I jumped the gun a bit; I still need to add the triangle reference into `MeshGL` so the tests can pass. Shouldn't be hard, hopefully I'll get to that tomorrow.

The next PR will be addressing #282 by adding a transforms vector that corresponds to the `meshID` vector. I think I'll even add some optional parameters to `GetMeshGL()` to specify which properties are normals so I can update them automatically.

**Comment by elalish** [comment]
@geoffder FYI, I removed the `MeshRelation` API and removed them from your cbindings too, but you'll probably want to add in the other API changes.

**Comment by geoffder** [comment]
Is `Mesh` on it's way to be a purely internal class? I see that `LevelSet` still returns one, and there remains a `Mesh` constructor for `Manifold`, yet `Smooth` has been switched to take `MeshGL`.

**Comment by elalish** [comment]
I'm considering it. Definitely I'll update things like `LevelSet` to return one. The other constructor was superfluous since `MeshGL` already has a constructor that takes a `Mesh`, so really both are supported anyway.

**Comment by geoffder** [comment]
Huh, giving a `Mesh` to `Smooth` still compiles? Pardon my ignorance, but does C++ implicitly find the single argument constructor of `MeshGL` and just use that? Never would have expected that.

**Comment by elalish** [comment]
Yup, indeed it does. I think it's basically the same system that let's you pass `2` (an int) when the function wants a float.

**Comment by geoffder** [comment]
Interesting that it does the same on it's own for user defined types with no "class/inheritance relationship". Maybe just surprising to me due to my minimal C++ experience.

**Comment by geoffder** [comment]
@elalish Opened a PR with the new meshgl accessors: https://github.com/elalish/manifold/pull/311. Let me know if I've missed something!

**Comment by pca006132** [comment]
I won't be able to review this soon, I am currently on vacation for 7 days in Japan without my computer.

**Comment by elalish** [comment]
@pca006132 No problem, enjoy your vacation!

**Comment by elalish** [comment]
Good news: `meshID` is no longer needed as part of the public API - it is now internal-only. Likewise, no need for `triProperties` and such in the public API as we can use `MeshGL` for this input instead. I'm keeping the explicit `Mesh` constructors for now simply because they avoid some computation. I'd recommend that `Mesh` remain a C++-only construct though. For bindings to other libraries, better to directly create a `Manifold` and use `MeshGL` as the only I/O struct.

**Pull request merged**
