### PR TITLE
optimize triangulator for msvc

### PR DESCRIPTION
**Pull request by pca006132**
It seems that msvc does not optimize `glm::determinant(glm::mat2(a, b))` well, it requires an intermediate struct that is stored in the stack, causing performance issues. This patch improves the performance of the test in #718 from 5s to 2s on Windows, and no performance degradation with clang/gcc.

@briansturgill maybe you can test this as well, I am using a windows vm so the performance number may not be that accurate.

### CODE REVIEW

**Comment by briansturgill** [comment]
@pca006132 You want just Windows, or Windows and Mac.

**Comment by pca006132** [comment]
@briansturgill just windows is fine

**Comment by briansturgill** [comment]
@pca006132 Good news... several runs, results in range 1500-1600 over 4x performance boost.

**Comment by pca006132** [comment]
Nice! Thanks a lot. Btw feel free to open discussions if you find other potential performance issues, even if they are platform specific. Tracy is a useful tool to find such issues.

**Comment by elalish** [comment]
Good find!

**Pull request merged**
