### PR TITLE
python: update nanobind version requirement

### LINKED ISSUE #1119: Please support nanobind 2.4.0
The nanobind dependency is limited to versions at or below 2.2.0:

https://github.com/elalish/manifold/blob/f48111c43c39ff515e2a84d5f35723b77ec57c2a/pyproject.toml#L29

It seems this limit was set out of caution in https://github.com/elalish/manifold/pull/987#issuecomment-2422510770

Discovered in https://github.com/NixOS/nixpkgs/pull/366800

### PR DESCRIPTION
**Pull request by pca006132**
Fixes #1119.

### CODE REVIEW

**Comment by pbsds** [comment]
Thank you for the swift response :smile: 

Package distributions such as nixpkgs really appreciate it if you tag dependency bumps like this with e.g. a patch release.

**Comment by pca006132** [comment]
> Package distributions such as nixpkgs really appreciate it if you tag dependency bumps like this with e.g. a patch release. If this is not possible, then we can always cherry-pick the change :)

Sounds good to me. @elalish what do you think?

**Comment by elalish** [comment]
Sure. Somehow we've had 50 PRs already since v3.0 (!). A few good bug fixes in there too - probably good to put out a patch anyway. @pca006132 Want me to write some release notes or do you want to do it?

**Comment by pca006132** [comment]
@elalish yeah you can do it, I wanr to spend more time on the sdf stuff.

**Pull request merged**
