### PR TITLE
Transform relations

### LINKED ISSUE #282: Incomplete mesh relations API
There is no transformation matrix in a MeshRelation object, which is needed for correctly restoring vertex normals. The only alternative at the moment is to separately track each transformation, and apply them to the vertex normals at the end.

There is also no flag for knowing whether a triangle needs to be flipped or not (for example, subtracted triangles are flipped, but not if there is a double-subtraction/quadruple-subtraction/etc...). The only alternatives are:
- compare the face normal of a triangle to the original face normal (with transformations applied), and use a dot product to check whether the triangle was flipped
- manually track which triangles need to be flipped by walking through each subtraction separately

### PR DESCRIPTION
**Pull request by elalish**
Related #282 

This adds transformation feedback to to the `MeshGL` output, as well as taking these transforms and original IDs as input. The `ReserveIDs` function allows you to make your own IDs to pass in for when your input mesh has multiple materials, for instance. 

I think this is moving the API in the right direction, because the tests are getting cleaner while checking more things. I still need to add feedback about if the reference is inverted to complete the normal transforms for #282.

### CODE REVIEW

**Comment by elalish** [comment]
@geoffder I updated cbind enough it would build, but there are some API updates here, which I presume is causing the CI failure.

**Comment by elalish** [comment]
Possibly related to #302: I noticed the ubuntu OMP builds have started to flake out sometimes, appearing to infinite-loop on `Samples.Bracelet`, but only about 50% of the time. I've marked them not required for now, but I need to come back and investigate.

**Comment by geoffder** [comment]
@elalish The [CI error](https://github.com/elalish/manifold/actions/runs/4116754328/jobs/7107206929#step:7:14) 
```
 [ RUN      ] CBIND.level_set
unknown file: Failure
C++ exception with description "Error in file: /__w/manifold/manifold/test/meshIO/src/meshIO.cpp (207): 'validChannels' is false: Invalid colorChannels." thrown in the test body.
[  FAILED  ] CBIND.level_set (1849 ms)
```
doesn't reproduce on my machine compiled with the current master. My first naive inclination was to try using the `MeshGL` extracted from a `Manifold` constructed from the level set mesh, rather than directly exporting it, thinking that the process may fill in whatever was missing (I have not looked into it) but it doesn't appear to hit the same error for me. Not sure what would be different for me vs the CI given that the exception is coming from within Manifold code (not something external like assimp which may have version mismatch).

On the topic of parallel backends, I found that testing hung out on `Samples.Knot42` when built with `OMP`, and `Samples.Bracelet` when built with `TBB`.

**Comment by elalish** [comment]
@geoffder I ran into this in #317 and solved it there. Turns out it was because I changed the API to return a `uint_32t` instead of an `int` - apparently C++ prefers to convert `int` to `uint` during a compare rather than the other way around. :/

**Comment by geoffder** [comment]
@elalish Ahh interesting, good catch! I wonder if that behaviour changed between compiler versions then since I didn't hit the bug.

**Pull request merged**
