### PR TITLE
Adding a test

### LINKED ISSUE #139: RecursiveEdgeSwap invalid memory access
Compile the following code with address sanitizer enabled:

```c++
#include <algorithm>

#include "manifold.h"

using namespace manifold;

std::vector<Manifold> RoundedFrameComponents(float edgeLength, float radius,
                                             int circularSegments) {
  Manifold edge = Manifold::Cylinder(edgeLength, radius, -1, circularSegments);
  Manifold corner = Manifold::Sphere(radius, circularSegments);

  std::vector<Manifold> edge1({corner, edge});
  for (Manifold& m : edge1) {
    m.Rotate(-90).Translate({-edgeLength / 2, -edgeLength / 2, 0});
  }

  std::vector<Manifold> edge2;
  for (Manifold m : edge1) {
    edge2.push_back(Manifold(m).Rotate(0, 0, 180));
    edge2.push_back(
        Manifold(m).Translate({-edgeLength / 2, -edgeLength / 2, 0}));
  }

  std::vector<Manifold> edge4;
  for (Manifold m : edge2) {
    edge4.push_back(Manifold(m).Rotate(0, 0, 90));
    edge4.push_back(Manifold(m));
  }

  std::vector<Manifold> frame;
  for (Manifold m : edge4) {
    frame.push_back(Manifold(m).Translate({0, 0, -edgeLength / 2}));
    frame.push_back(Manifold(m).Rotate(180));
  }

  return frame;
}

int main() {
  auto components = RoundedFrameComponents(100, 10, 4);

  std::vector<unsigned int> indices({5, 8, 10, 2, 1});

  Manifold m;
  for (auto i : indices) {
    m = m + components[i];
    // just to force evaluate
    m.NumVert();
  }
  return 0;
}
```

```
cmake -DCMAKE_BUILD_TYPE=Release -DMANIFOLD_PAR="NONE" -DMANIFOLD_USE_CUDA=OFF -DCMAKE_CXX_FLAGS="-g -fsanitize=address" -DCMAKE_CXX_COMPILER="clang++" ..
```

and it will abort with the following message:
```
==1210305==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c000002878 at pc 0x000000566be3 bp 0x7ffffffed250 sp 0x7ffffffed248
READ of size 4 at 0x61c000002878 thread T0
[Detaching after fork from child process 1210309]
    #0 0x566be2 in manifold::Manifold::Impl::RecursiveEdgeSwap(int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:386:23
    #1 0x56691f in manifold::Manifold::Impl::RecursiveEdgeSwap(int) /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:476:3
    #2 0x560b71 in manifold::Manifold::Impl::SimplifyTopology() /home/pca006132/code/test/manifold/manifold/src/edge_op.cpp:186:5
    #3 0x5a00c6 in manifold::Boolean3::Result(manifold::Manifold::OpType) const /home/pca006132/code/test/manifold/manifold/src/boolean_result.cpp:688:8
    #4 0x50abd1 in manifold::Manifold::Boolean(manifold::Manifold const&, manifold::Manifold::OpType) const /home/pca006132/code/test/manifold/manifold/src/manifold.cpp:467:50
    #5 0x50af9a in manifold::Manifold::operator+(manifold::Manifold const&) const /home/pca006132/code/test/manifold/manifold/src/manifold.cpp:475:10
    #6 0x504b7f in main /home/pca006132/code/test/manifold/tools/union.cpp:47:11
    #7 0x7ffff7c8978f in __libc_start_main (/nix/store/qjgj2642srlbr59wwdihnn66sw97ming-glibc-2.33-123/lib/libc.so.6+0x2778f)
    #8 0x423279 in _start /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120
```

Tested on both ed272b0 and the current master.

Also, different union order will give a different number of vertices. I suspect this is also related to the problem in https://github.com/elalish/manifold/pull/131#issuecomment-1153467932 . Changing the order in `BatchBoolean` will *randomly* fail some tests, for example by sorting the manifolds instead of using a heap, I managed to get Samples.Sponge4 passed but failed the Samples.FrameReduced test, not sorting/using a heap will lead to a different kind of failure for example.

This case is found by getting a set of manifolds, and repeatedly do a random shuffle and union them until it fails (or executed enough rounds so it can be considered not buggy). And then you can try to reduce the case by doing a random shuffle and discard the last element, similarly until you can no longer reproduce the error after discarding the last element.

### PR DESCRIPTION
**Pull request by elalish**
I'm adding this test: https://github.com/elalish/manifold/issues/139#issuecomment-1167097407 because I can't repro any problem with it on my local machine (with or without CUDA), so I'm checking to see if the CI can repro the issue.

Fixes #139

I fixed the seg fault, which turned out to be a one-liner. The CI validates it, though I can't repro locally.

### CODE REVIEW

**Comment by elalish** [comment]
Indeed, the CI repros the issue (on some, but not all builds). I really need to hunt down the source of this non-determinism...

**Comment by pca006132** [comment]
Maybe you can try to run it in a docker, to get the CI environment.

**Comment by elalish** [comment]
I'll do that next time if needed, but thankfully your sanitizer output pointed me right to the issue.

**Comment by elalish** [comment]
By the way, thank you @deadman2000 for the simple repro!

**Pull request merged**
