### PR TITLE
Update manifoldc to MeshGL breaking changes

### PR DESCRIPTION
**Pull request by geoffder**
Had a moment so I thought I would get the C bindings compiling again on this branch.

### CODE REVIEW

**Comment by elalish** [comment]
Thanks! Shall I go ahead and merge this into my branch now or wait for you to update it first? #290 is finally working, but I've simplified the `MeshRelation` because it turns out it was broken anyway, so I think that'll need an update on this side.

**Comment by geoffder** [comment]
Ok, I'll try to update it to reflect the further changes tomorrow then.

**Comment by geoffder** [comment]
Rebased and updated to your latest work @elalish.

**Review by elalish — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
