### PR TITLE
fix openscad build

### PR DESCRIPTION
**Pull request by pca006132**
https://github.com/openscad/openscad/issues/4679#issuecomment-1694420791

1. Do not use PSTL if tbb version is too old.
2. Only use tbb concurrent containers if the header exists.
3. Avoid leaking `MANIFOLD_FLAGS` to downstream consumers.

I think we should probably put `public.h` into a separate directory as well, as other headers in utilities are not supposed to be visible to users.

@t-paul can you verify if this patch fixes the compilation errors for you?

### CODE REVIEW

**Comment by t-paul** [comment]
I think I have correctly switched the submodule but I'm still getting the build error.
```
$ git submodule 
 1ea402208c3127ffb443931e9bb1681c191dacca libraries/MCAD (openscad-2019.05-78-g1ea4022)
 7b24d76556e885195c80952494454baf1544067c submodules/OpenCSG (heads/master)
 553af165116c159d800d6c3b928ad10035dfbf5f submodules/manifold (v1.0.0-466-g553af16)
 fe61be80bf8942e764e18d469e96f8dacab44728 submodules/mimalloc (v1.7.7)
 c3dc841af4dbf44669e65b82cb68a575864326bd submodules/sanitizers-cmake (heads/master)
```

Build log:
```
/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++  -I/openscad/mingw64.static.posix/submodules/manifold/src/collider -I/openscad/submodules/manifold/src/collider -I/openscad/submodules/manifold/src/collider/include -I/openscad/submodules/manifold/src/utilities/include -I/openscad/submodules/manifold/src/third_party/thrust/dependencies/libcudacxx/include -I/openscad/submodules/manifold/src/third_party/thrust -I/openscad/submodules/manifold/src/third_party/glm/glm/.. -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++ -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/x86_64-w64-mingw32.static.posix -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/backward -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include -isystem /
mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include-fixed -isystem /mxe/usr/x86_64-w64-mingw32.static.posix/include -frounding-math -Wno-attributes -O3 -DNDEBUG -O3 -Werror -Wall -Wno-sign-compare -Wno-unused -Wno-array-bounds -Wno-stringop-overflow "-DMANIFOLD_PAR='T'" -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB -MD -MT submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj -MF submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj.d -o submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj -c /openscad/submodules/manifold/src/collider/src/collider.cpp                                    
In file included from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/parallel_backend.h:20,                                             
                 from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/algorithm_impl.h:22,
                 from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/glue_execution_defs.h:50,
                 from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/execution:32,                                                                                                            
                 from /openscad/submodules/manifold/src/utilities/include/par.h:34,                                                                                                                                
                 from /openscad/submodules/manifold/src/utilities/include/sparse.h:19,                                                                                                                             
                 from /openscad/submodules/manifold/src/collider/include/collider.h:17,                                                                                                                            
                 from /openscad/submodules/manifold/src/collider/src/collider.cpp:15:                    
/mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/parallel_backend_tbb.h:29:6: error: #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.         
   29 | #    error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported. 
      |      ^~~~~                                                                                                                                                                                                 
```

How can I check that `pstl` is disabled?

**Comment by t-paul** [comment]
Ouchies!
```
/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++ -D__TBB_BUILD -D__TBB_DYNAMIC_LOAD_ENABLED=0 -D__TBB_SOURCE_DIRECTLY_INCLUDED=1 -D__TBB_USE_ITT_NOTIFY -I/openscad/mingw64.static.posix/_deps/tbb-build/src/tbb -I/openscad/mingw64.static.posix/_deps/tbb-src/src/tbb -I/openscad/mingw64.static.posix/_deps/tbb-src/src/tbb/../../include -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++ -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/x86_64-w64-mingw32.static.posix -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/backward -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include-fixed -isystem /mxe/usr/x86_64-w64-mingw32.static.posix/include -frounding-math -Wno-attributes -O3 -DNDEBUG -flifetime-dse=1 -Wall -Wextra -Wfatal-errors -mrtm -mwaitpkg -fstack-clash-protection -fno-strict-overflow -fno-delete-null-pointer-checks -fwrapv -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -D_FORTIFY_SOURCE=2 -std=c++11 -MD -MT _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj -MF _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj.d -o _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj -c /openscad/mingw64.static.posix/_deps/tbb-src/src/tbb/arena.cpp
during RTL pass: final
In file included from /openscad/mingw64.static.posix/_deps/tbb-src/src/tbb/arena.cpp:17:
/openscad/mingw64.static.posix/_deps/tbb-src/src/tbb/task_dispatcher.h: In static member function 'static void tbb::detail::r1::task_dispatcher::local_wait_for_all<true, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&)::<lambda()>::_FUN()':
/openscad/mingw64.static.posix/_deps/tbb-src/src/tbb/task_dispatcher.h:358:35: internal compiler error: in seh_emit_stackalloc, at config/i386/winnt.c:1056
  358 |                 do_throw_noexcept([] { throw; });
      |                                   ^~~~~~~~~~~~~
0x17608f6 internal_error(char const*, ...)
        ???:0
0x676f80 fancy_abort(char const*, int, char const*)
        ???:0
0x1095b14 i386_pe_seh_unwind_emit(_IO_FILE*, rtx_insn*)
        ???:0
0xa3487b final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
ninja: build stopped: subcommand failed.
```
Maybe it's time to look at submitting an updated TBB package to MXE... that would remove the need for the `pkg-config` trickery too. I've never used TBB directly, but I suppose that's not really required for packaging :grinning:.

**Comment by pca006132** [comment]
> I think I have correctly switched the submodule but I'm still getting the build error.
> 
> ```
> $ git submodule 
>  1ea402208c3127ffb443931e9bb1681c191dacca libraries/MCAD (openscad-2019.05-78-g1ea4022)
>  7b24d76556e885195c80952494454baf1544067c submodules/OpenCSG (heads/master)
>  553af165116c159d800d6c3b928ad10035dfbf5f submodules/manifold (v1.0.0-466-g553af16)
>  fe61be80bf8942e764e18d469e96f8dacab44728 submodules/mimalloc (v1.7.7)
>  c3dc841af4dbf44669e65b82cb68a575864326bd submodules/sanitizers-cmake (heads/master)
> ```
> 
> Build log:
> 
> ```
> /mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++  -I/openscad/mingw64.static.posix/submodules/manifold/src/collider -I/openscad/submodules/manifold/src/collider -I/openscad/submodules/manifold/src/collider/include -I/openscad/submodules/manifold/src/utilities/include -I/openscad/submodules/manifold/src/third_party/thrust/dependencies/libcudacxx/include -I/openscad/submodules/manifold/src/third_party/thrust -I/openscad/submodules/manifold/src/third_party/glm/glm/.. -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++ -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/x86_64-w64-mingw32.static.posix -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/backward -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include -isystem /
> mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include-fixed -isystem /mxe/usr/x86_64-w64-mingw32.static.posix/include -frounding-math -Wno-attributes -O3 -DNDEBUG -O3 -Werror -Wall -Wno-sign-compare -Wno-unused -Wno-array-bounds -Wno-stringop-overflow "-DMANIFOLD_PAR='T'" -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB -MD -MT submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj -MF submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj.d -o submodules/manifold/src/collider/CMakeFiles/collider.dir/src/collider.cpp.obj -c /openscad/submodules/manifold/src/collider/src/collider.cpp                                    
> In file included from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/parallel_backend.h:20,                                             
>                  from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/algorithm_impl.h:22,
>                  from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/glue_execution_defs.h:50,
>                  from /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/execution:32,                                                                                                            
>                  from /openscad/submodules/manifold/src/utilities/include/par.h:34,                                                                                                                                
>                  from /openscad/submodules/manifold/src/utilities/include/sparse.h:19,                                                                                                                             
>                  from /openscad/submodules/manifold/src/collider/include/collider.h:17,                                                                                                                            
>                  from /openscad/submodules/manifold/src/collider/src/collider.cpp:15:                    
> /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/pstl/parallel_backend_tbb.h:29:6: error: #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.         
>    29 | #    error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported. 
>       |      ^~~~~                                                                                                                                                                                                 
> ```
> 
> How can I check that `pstl` is disabled?

it is weird, I did add a tbb version check in `par.h` and only enable pstl when the tbb version is large enough.

**Review by elalish — APPROVED** [review]
LGTM. Agreed that `public.h` should live in a separate folder from the internal utils headers.

**Comment by pca006132** [comment]
I think the windows failure is due to https://github.com/AngusJohnson/Clipper2/issues/601

**Comment by pca006132** [comment]
@t-paul I think I know the reason why pstl was not disabled, I forgot to check for TBB version before including `<execution>`. Can you check again to see if this works now?

**Comment by pca006132** [comment]
ok it seems that both max and min are problematic on windows...

**Comment by pca006132** [comment]
Oh OK, our CI does not include mingw, I guess that is why we did not catch this issue earlier.

I can run containers. Not sure if I can run windows container without a VM, but yeah it would be easier if you can paste the instructions here.

**Comment by t-paul** [comment]
Good news, I think it got past `collider.cpp` now, but still some compile error in `csg_tree.cpp`.

```
/mxe/usr/x86_64-pc-linux-gnu/bin/x86_64-w64-mingw32.static.posix-g++  -I/openscad/mingw64.static.posix/submodules/manifold/src/manifold -I/openscad/submodules/manifold/src/manifold -I/openscad/submodules/manifol
d/src/manifold/include -I/openscad/submodules/manifold/src/utilities/include -I/openscad/submodules/manifold/src/third_party/thrust/dependencies/libcudacxx/include -I/openscad/submodules/manifold/src/third_party
/thrust -I/openscad/submodules/manifold/src/third_party/glm/glm/.. -I/openscad/submodules/manifold/src/cross_section/include -I/openscad/submodules/manifold/src/third_party/clipper2/CPP/Clipper2Lib/include -I/op
enscad/submodules/manifold/src/collider/include -I/openscad/submodules/manifold/src/polygon/include -I/openscad/submodules/manifold/src/third_party/graphlite/include -I/openscad/submodules/manifold/src/third_par
ty/quickhull -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++ -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/x86_64-w64-mingw32.static.posix -isystem /mx
e/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include/c++/backward -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0/include -isystem /mxe/usr/lib/gcc/x86_64-w64-mingw32.static.posix/11.2.0
/include-fixed -isystem /mxe/usr/x86_64-w64-mingw32.static.posix/include -frounding-math -Wno-attributes -O3 -DNDEBUG -Werror -Wall -Wno-sign-compare -Wno-unused -Wno-array-bounds -Wno-stringop-overflow -O3 "-DM
ANIFOLD_PAR='T'" -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB -MD -MT submodules/manifold/src/manifold/CMakeFiles/manifold.dir/src/csg_tree.cpp.obj -MF submodules/manifold/src/manifold/CMakeFiles/manifold.dir
/src/csg_tree.cpp.obj.d -o submodules/manifold/src/manifold/CMakeFiles/manifold.dir/src/csg_tree.cpp.obj -c /openscad/submodules/manifold/src/manifold/src/csg_tree.cpp                                            
/openscad/submodules/manifold/src/manifold/src/csg_tree.cpp: In static member function 'static std::shared_ptr<manifold::Manifold::Impl> manifold::CsgOpNode::BatchBoolean(manifold::OpType, std::vector<std::share
d_ptr<const manifold::Manifold::Impl> >&)':                                                                                                                                                                        
/openscad/submodules/manifold/src/manifold/src/csg_tree.cpp:463:74: error: no matching function for call to 'tbb::interface5::concurrent_priority_queue<std::variant<std::shared_ptr<const manifold::Manifold::Impl
>, std::shared_ptr<manifold::Manifold::Impl> >, manifold::CsgOpNode::BatchBoolean(manifold::OpType, std::vector<std::shared_ptr<const manifold::Manifold::Impl> >&)::<lambda(const SharedImpl&, const SharedImpl&)>
 >::concurrent_priority_queue(manifold::CsgOpNode::BatchBoolean(manifold::OpType, std::vector<std::shared_ptr<const manifold::Manifold::Impl> >&)::<lambda(const SharedImpl&, const SharedImpl&)>&)'               
  463 |   tbb::concurrent_priority_queue<SharedImpl, decltype(cmpFn)> queue(cmpFn);                                                                                                                                
      |                                                                          ^                                                                                                                                 
In file included from /mxe/usr/x86_64-w64-mingw32.static.posix/include/tbb/tbb.h:46,                                                                                                                               
                 from /openscad/submodules/manifold/src/manifold/src/csg_tree.cpp:16:                                                                                                                              
/mxe/usr/x86_64-w64-mingw32.static.posix/include/tbb/concurrent_priority_queue.h:103:5: note: candidate: 'template<class InputIterator> tbb::interface5::concurrent_priority_queue<T, Compare, A>::concurrent_prior
ity_queue(InputIterator, InputIterator, const allocator_type&) [with InputIterator = InputIterator; T = std::variant<std::shared_ptr<const manifold::Manifold::Impl>, std::shared_ptr<manifold::Manifold::Impl> >; 
Compare = manifold::CsgOpNode::BatchBoolean(manifold::OpType, std::vector<std::shared_ptr<const manifold::Manifold::Impl> >&)::<lambda(const SharedImpl&, const SharedImpl&)>; A = tbb::cache_aligned_allocator<std
::variant<std::shared_ptr<const manifold::Manifold::Impl>, std::shared_ptr<manifold::Manifold::Impl> > >]'                                                                                                         
  103 |     concurrent_priority_queue(InputIterator begin, InputIterator end, const allocator_type& a = allocator_type()) :                                                                                        
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                              
/mxe/usr/x86_64-w64-mingw32.static.posix/include/tbb/concurrent_priority_queue.h:103:5: note:   template argument deduction/substitution failed:                                                                   
/openscad/submodules/manifold/src/manifold/src/csg_tree.cpp:463:74: note:   candidate expects 3 arguments, 1 provided                                                                                              
  463 |   tbb::concurrent_priority_queue<SharedImpl, decltype(cmpFn)> queue(cmpFn);                                                                                                                                
```
---
MXE is a cross-build environment running MinGW on Linux + providing a packaging system, so it does not require Windows at all.

Run ad-hoc base container with all packages needed for OpenSCAD compiled:
```
docker run -it openscad/mxe-x86_64-gui:latest
```

Commands that are used to build, including updating the git repo to this PR:
```
cd /
rm -rf openscad
git clone https://github.com/openscad/openscad
cd openscad
git checkout update-manifold
git submodule update --init --recursive
git log -n8 --pretty=tformat:"%h %ai (%aN) %s"
export LC_ALL=C.UTF-8
export MXEDIR=/mxe
export LIB3MF_INCLUDEPATH=/mxe/usr/x86_64-w64-mingw32.static.posix/include/lib3mf
export LIB3MF_LIBPATH=/mxe/usr/i686-w64-mingw32.static.posix/lib
export PKG_CONFIG_PATH=/mxe/usr/x86_64-w64-mingw32.static.posix/lib/pkgconfig 
bash -c 'ln -sfv $PKG_CONFIG_PATH/{intel-,}tbb.pc' 
bash -c 'ln -sfv /usr/bin/python{3,}' 
# update to manifold PR
git submodule deinit -f submodules/manifold
rm -rf submodules/manifold/
git submodule add -f -b compile-options --name manifold -- https://github.com/pca006132/manifold submodules/manifold
git submodule update --init --recursive
git submodule 
# run build
./scripts/release-common.sh -v "" mingw64 snapshot
```
I literally just copy all those lines and paste them into a freshly started container.

**Comment by pca006132** [comment]
@t-paul the build should now succeed. The MXE build environment is also added to our CI, which can hopefully catch this kind of issues for our subsequent changes.

**Comment by t-paul** [comment]
Awesome, thank you! I'll give it a try and see if someone can verify the build is running fine. I still have some issues with running those in my Windows VM, probably due to some legacy OpenGL code in OpenSCAD which is currently in the process of being removed. So there's some hope I can do some limited testing again soon-ish.

**Comment by pca006132** [comment]
good, I guess I will merge this first, and feel free to open an issue when you found any bug (except https://github.com/elalish/manifold/issues/535 which is known for now)

**Comment by t-paul** [comment]
Builds look good for the AppImage and Windows build :tada:.

There an issue that's crashing the application after mutliple runs we still need to investigate, but that's unlikely to be related to those changes here and/or even Manifold itself.

Many thanks for getting the builds working on those older or slightly strange platforms working.

**Comment by elalish** [comment]
Indeed, well done @pca006132!

**Pull request merged**
