### PR TITLE
added maze benchmark

### PR DESCRIPTION
**Pull request by pca006132**
I was talking to my friend and realized we need some updated benchmarks to tell others how fast we are :P

I ported the maze benchmark from https://gist.github.com/ochafik/2db96400e3c1f73558fcede990b8a355
I didn't bother to run the benchmark with OpenSCAD on my computer, it took 1167ms on my computer to run it with manifold, and 15s when I increase `fn` to 128, which is a lot faster than the 5 minutes with fast-csg enabled.

We should probably deal with #216 as well, put some nice graphs or something.

### CODE REVIEW

**Comment by elalish** [comment]
Good idea! The best pretty graphs I have are [here](https://elalish.blogspot.com/2022/03/manifold-performance.html), but they're pretty out of date now. We should probably put some up on our README. 

By the way, how's our Python API these days? I haven't touched it lately and our API has changed a fair bit. This benchmark looks like it could be the start of some automated testing for it. It would be nice to finally publish it to pypi.

**Review by elalish — APPROVED** [review]

**Comment by pca006132** [comment]
The Python API is actually very stable, but lacks some advanced functionalities we recently added, we can add them back before publishing to pypi. There is always automated testing for it: https://github.com/elalish/manifold/blob/master/.github/workflows/manifold.yml#L48, and I'm still using the Python API as I like operator overloading :)

**Comment by elalish** [comment]
Excellent, I forgot you already added that testing. Might be nice to convert some of our JS examples to python to test our more advanced APIs once they're added. Do you want to try updating it for pypi release along with npm v2, or will that take awhile still?

**Comment by pca006132** [comment]
No, I am a bit busy now and can only squeeze a bit of time to do side projects, so that will take me a while.

**Comment by elalish** [comment]
Okay, no prob - thanks for letting me know!

**Pull request merged**
