### PR TITLE
add formatting script

### PR DESCRIPTION
**Pull request by pca006132**
This also fix the version for clang-format to 14. I think this script should work for other distros if they have clang-14 installed, would be nice if someone can help me test it.

### CODE REVIEW

**Comment by wrongbad** [comment]
On MacOS, it's not super convenient to get clang-14. Brew has v8, v11, and v17. `pip install 'clang-format==14.*'` works though, but it just puts a `clang-format` in the virtual env and on the `PATH` so it won't be found the way your script works.
I was using v11 because it wasn't diverging from the v12 in the CI.

All that to say I'm not sure what the answer is here.

**Comment by pca006132** [comment]
Interesting, I thought the CI is using v14.
I think the script can add a fallback to pip if clang-14 is not found?

**Comment by pca006132** [comment]
I think I can just make it use v11.

**Review by elalish — APPROVED** [review]
Thanks!

**Pull request merged**
