### PR TITLE
hashtable atomic load store fix

### PR DESCRIPTION
**Pull request by pca006132**
Note that I intentionally leave this behind master for GitHub action to check.

### CODE REVIEW

**Comment by pca006132** [comment]
It seems that there is also another problem: because the use count is incremented after setting the keys, the hashtable can be already full before the use count indicates it is full, causing infinite loop. A simple fix is to check for full for every iteration, though it may be better to just increment the use count before entering the loop and check for full.

**Comment by pca006132** [comment]
No idea why is there undefined reference to those atomic functions, I have already added `-latomic` to the linker flags...

**Comment by elalish** [comment]
CMake says it found `atomic_load_8`, but then the build fails looking for atomic store. Maybe they're in different places?

**Comment by pca006132** [comment]
Unlikely, I will get a Ubuntu container to debug later. Or you can try to debug this if you have time, just look at the symbols libatomic provides on Ubuntu and perhaps try to google it and see if others encountered similar issues...

**Comment by pca006132** [comment]
Oh and I actually thought that GCC can compile these into instructions instead of function calls. Maybe I should make them acquire release for better performance and avoid such a pain in compiling them.

**Comment by pca006132** [comment]
hmmm, we don't need atomic load/store for values, just keys is fine.

**Comment by pca006132** [comment]
Seems working, will clean this up tmr and should be ready to merge at that time.

**Comment by elalish** [comment]
Perfect, thanks! And remember to pull master.

**Review by elalish — APPROVED** [review]
Thanks!

**Pull request merged**
