### PR TITLE
change extrude behavior

### PR DESCRIPTION
**Pull request by pca006132**
#632 

This change the extrude behavior to match openscad linear extrude.

### CODE REVIEW

**Comment by pca006132** [comment]
Not yet addressing the shortest diagonal part. I think we should probably also use this shortest diagonal thing for rotate extrude.

**Review by elalish — APPROVED** [review]
Do you have an image showing the before/after difference?

**Comment by pca006132** [comment]
I had, but it is not here with me now. Will reply here tonight.

**Comment by pca006132** [comment]
```
const a = 110;
const a2 = 150;
const h = 30;
const R = 20;
const r = 2;
const result = Manifold.extrude(
  CrossSection.circle(r).translate([R*Math.sin(a2), R*Math.cos(a2)]), h, 100, a, [0, 1])
  .add(Manifold.cube([1, 1, h]));

```

Before:
image


After:
image

**Comment by pca006132** [comment]
@elalish btw this also changes the extrude direction, not sure if we should do this as some users may rely on the extrude direction.

**Comment by pca006132** [comment]
In terms of openscad compatibility, we can just negate the sign of the twist angle.

**Comment by pca006132** [comment]
OK I reverted the direction change, it is not worth breaking existing code.

**Review by elalish — APPROVED** [review]
Thanks, yeah CCW seems more logical to me anyway.

**Pull request merged**
