### PR TITLE
updated python doc strings

### PR DESCRIPTION
**Pull request by elalish**
Fixes some more of #361, but I'd still like to get a `MeshGL` binding in before we publish to pypi.

### CODE REVIEW

**Comment by pca006132** [comment]
It seems that we should also change the name of `pymanifold.cpp` to `manifold3d.cpp`, or there will be weird import errors. Otherwise this looks good to me.

**Comment by elalish** [comment]
Good call, thanks!

**Comment by axel-angel** [comment]
aaa breaking change :sweat_smile: 

> It seems that we should also change the name of pymanifold.cpp to manifold3d.cpp, or there will be weird import errors. Otherwise this looks good to me.

it's probably obvious but can you explain?

**Comment by pca006132** [comment]
@axel-angel This is because we want to use the same name across NPM and PyPi later, so we want to change the module name. Changing the module name also require changing the filename due to how python works.

**Comment by elalish** [comment]
Exactly, I'm trying to get our breaking changes out of the way before doing our first pypi release.

**Pull request merged**
