### PR TITLE
Do nothing if the half edge array is empty.

### PR DESCRIPTION
**Pull request by fire**
Let's see if this fixes the bug.

### CODE REVIEW

**Comment by elalish** [comment]
What bug was this fixing? Can you add a test case to demonstrate?

**Review by elalish — CHANGES_REQUESTED** [review]
What bug is this fixing?

**Comment by fire** [comment]
I don't have the test case on hard, it was with an empty manifold.

**Comment by elalish** [comment]
Can you please add a test so we know what problem we're fixing? You should be able to copy this one and tweak slightly: https://github.com/elalish/manifold/blob/master/test/mesh_test.cpp#L608

**Comment by fire** [comment]
I'm not able to work on this much because of siggraph 2022 this week.

**Comment by elalish** [comment]
Got it, no prob. I'm curious, mostly :)

**Comment by fire** [comment]
I wasn't able to get myself to work on this. Godot Engine 4 work has been tiring.

**Pull request closed without merging**
