### PR TITLE
[FEAT] Add Sweep Operation

### PR DESCRIPTION
**Pull request by zalo**
This PR is an attempt to break out a successful experiment from Python.
https://github.com/elalish/manifold/issues/192#issuecomment-1823327943

- Does this make sense to move to Impl with parallel for-loops?
- Should I add full transform (translation/rotation/scale) variant with a `$fn` for more interesting sweep trajectories?
- Maybe Catmull-Rom Spline Interpolation between Segments? (Could also be left to the user)

### CODE REVIEW

**Comment by zalo** [comment]
I think Swept profiles are called "Pipe"s in CAD; having a sweep on the `CrossSection` would be fun too.

Swept Volumes aren't used suuper often, but there also aren't many libraries that can do them (I think [Siemens NX](https://www.youtube.com/watch?v=yOmabwGMQgw) is the only CAD package with it).
In modelling, I believe they're typically used for cutting out the profile of one body against another that needs to slide or rotate near it.

Like, cutting funny shaped gears:
https://www.shadertoy.com/view/ldsBRr
Or the interesting animations shown in the last example here:
https://www.youtube.com/watch?v=6iLqMQ3kd24

It seems like the interesting stuff requires full transform support, so I'll see about adding that...

**Comment by elalish** [comment]
Based on your examples, it sounds like another way to achieve this is through #426 - particularly if we support both of OpenSCAD's [options](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_the_2D_Subsystem#3D_to_2D_Projection). For a sliding part, you could extrude the projection with cut = false. This feels like a more intuitive and flexible API to me, which is part of why I think this is a rare function.

I'm thinking we'd probably make this two functions: `Project()` and `Slice(float height)`, since they'd be implemented differently anyway. Would you be interested in implementing `Project()`? I think it would be just a 2D convex hull.

**Comment by pca006132** [comment]
But if `project` is implemented as 2D convex hull, it will not work for 2D shape that is not convex, and what about things like a torus that has a hole inside?

**Comment by elalish** [comment]
Oh right, I didn't think about that long enough. Hmm, I know how to do a slice, but what's the algorithm for a projection?

**Comment by pca006132** [comment]
I think openscad just project every triangle into 2D and union them.

**Comment by elalish** [comment]
@zalo I don't mean to be discouraging - that video is cool. Still, for `n` triangles, we're talking `n` convex hulls all unioned together? And that only gets us one step in the sweeps they're talking about, and doesn't even include rotation. How computationally feasible is this algorithm?

**Comment by pca006132** [comment]
I feel that the idea of using 2D projection for sweep, union that with the initial and final position should be faster.

**Comment by zalo** [comment]
2D projection + Extrude won’t work, see linked comment gif for counter example shape:
https://github.com/elalish/manifold/issues/192#issuecomment-1823327943
(Also, CrossSections lose 3D information?)

Also, I’m not familiar enough with Manifold’s internals to implement project and slice operators efficiently 😅
I’d probably try to do slicing by splitting by a plane, and then deleting all the vertices that are collocated with the original part, and projection by unioning the triangles in 2D as @pca006132 said…

Like Minkowski Sums, this might be part of a class of more expensive mesh algorithms…
Winding Number fills, Morphological Dilation/Erosion/Opening/Closing, Retopologizing, etc.

Though (save for the morphological ops), they tend to veer away from the “Exactish-CSG” spirit of the library (does simple things fast), so I’d understand if you’d rather tell users to use a different library, or write their own extension kernels in the client bindings languages…

**Comment by pca006132** [comment]
@zalo I am deep inside a debug session of something else, will response later tmr about the slice thing. I think slower operation is fine, we just want to make sure we are not missing some obvious better implementation.

**Comment by pca006132** [comment]
And I see why this sweep is not that simple now. Thanks.

**Comment by pca006132** [comment]
Thinking about it, I think we can have a fast and simple algorithm for this.

Say the direction is v, for every face we compute the dot product of its normal with v, positive means that we should offset the face, and negative means that it should stay. To avoid self-intersection, we use the collider to compute if the swept volume of a face (positive dot product) will intersect with another face, mark them and do not move them. After moving the faces, we stitch the gaps by checking the neighbors of the moved faces. Because the marked faces have a positive dot product with v, we can compute the sweep result of each connected component of marked faces and union with the previous result.

Just thought of this, not sure if it makes sense.

**Comment by elalish** [comment]
@zalo Yeah, this particular op feels like a combination of too specialized and not really any slower to implement outside of the core library. I think a polygon-sweep-along-path op will be more generally useful, but I want to achieve this via #289, because then it will be very fast and that will also solve a number of other important problems.

**Comment by zalo** [comment]
> Thinking about it, I think we can have a fast and simple algorithm for this.
>  Because the marked faces have a positive dot product with v, we can compute the sweep result of each connected component of marked faces and union with the previous result.
> 
> Just thought of this, not sure if it makes sense.

This actually sounds pretty good (though, I’m not sure it’ll work for the more general Translation+Rotation+Scale Matrix Sweep…)

My mesh-fu is a little weak… if we delete the backwards triangles, and isolate just the connected component regions, is there a straight-forward way to step along the component boundary?

I guess the boundary edges can be marked and remembered during the “backwards triangle deleting” process… That could work!  I’ll think about this a little more…

**Comment by zalo** [comment]
Oh, there's a couple more use-cases for sweeps that might be really fun:
- Drawing/Sculpting/Modelling Tools; Dreams has a "Smear" tool (which is Sweeping along VR Controller paths)
https://youtu.be/0BbxHRZB9UA?t=1289
https://youtu.be/_PNUVFYgI8w?t=153
https://youtu.be/v27LZivpffQ?t=208
https://youtu.be/v27LZivpffQ?t=1025

- CNC Toolpath Planning/Simulation:
image
image

**Comment by pca006132** [comment]
> Do you want to attack those or should I? I also have an idea for offset I want to try out.

You can do it. I am working on other stuff right now and don't have enough time for this.

**Comment by zalo** [comment]
Alright; I'll close for now since the 90% use-case is on Convex Tools/Solids, which can just be Hulled.

**Pull request closed without merging**
