### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by elalish**
This is a huge release! We've packed in all the [requested breaking changes](https://github.com/elalish/manifold/discussions/664) to put us on a solid path of API stability going forward. We have removed **all** of our required dependencies (no more Thrust or GLM!) and dramatically simplified our directory structure and CMake. We have upgraded internally to double precision and added `MeshGL64` for those who need to access it. And we have simplified and improved the API in many ways and added a few powerful new features. Please check out our new and improved [C++](https://manifoldcad.org/docs/html/classmanifold_1_1_manifold.html) and [TypeScript](https://manifoldcad.org/jsdocs) docs pages!

## Breaking Changes
- Use `size_t` instead of `int` across our API, @pca006132 in #833
- Made `CrossSection` (and Clipper2 dependency) optional, @elalish in #850
- Removed Thrust dependency, use optional TBB instead, @elalish, @pca006132 in #852, #856, #857
- Moved `LevelSet()` in as a static member of `Manifold`, @elalish in #876, #894
- Upgraded from single to double precision, @pca006132 in #895
- Simplify directory structure, @pca006132, @starseeker in #918, #961
- Remove property tolerance, @elalish in #935
- Remove `Mesh`, @elalish in #950
- Overhaul our CMake, @starseeker in #961, #965, #967, #980, #990, #1005
- Replace GLM with linalg - down another dependency, @elalish in #984
- Separate coplanarity from faceID, @elalish in #991
- Split `Precision` into `Epsilon` and `Tolerance`, @pca006132, @elalish in #997, #1008, #1007
- Switched property indexing from vector to scalar, @elalish in #1016
- Replace `GetProperties()` with `Volume()` and `SurfaceArea()`, @elalish in #1022
- SDF boundary cleanup, @elalish in #1037
- Disable exceptions by default, @elalish in #1044

## New Features
- SDF interpolation, @elalish in #866
- Add `MeshGL64`, @pca006132 in #927, #1038
- Add `RefineToTolerance()`, @elalish in #938
- Add `SetTolerance()`, @pca006132 in #997

## Bindings
- Fix missing 'this' for property access in wasm bindings, @dsafa in #914
- wasm: fix `CrossSection` slice and project bindings, @neilpa in #930
- Expose `Quality::ResetToDefaults()` via C bindings, @NickUfer in #964
- Wasm: update `CrossSection.toPolygons()` return value to match type, @dsafa in #963
- Expose allocation functions via C bindings, @NickUfer in #968
- Fix python binding, @pca006132 in #987
- Fixed memory leak in C bindings, @pca006132 in #1018
- Added some missing C and JS bindings, @elalish in #1023
- Added C bindings for `Triangulate()`, @james-bern in #1034

## Bug Fixes
- Triangulation fix, @elalish in #850
- Propagate errors, @pca006132 in #940
- Removed `RotateUp` and `uint`, @elalish in #1000
- Fix data races, @pca006132 in #1019
- Fix properties regression, @elalish in #1051

## Performance Improvements
- Normal calculation optimization, @pca006132 in #934
- Removed face from halfedge, @pca006132 in #939
- Collider optimization, @pca006132 in #978
- Removed deterministic param, @elalish in #1033
- Free temporary vectors earlier, @pca006132 in #1047

## Build/CI Updates
- Avoid Wundef trigger, @starseeker in #861
- Update to emscripten 3.1.61, @elalish in #860
- Fix debug mode msvc build error, @pca006132 in #863
- Fix shadowing warning, @elalish in #867
- Rename `operator""_z` to `_uz`, @BenFrantzDale in #869
- Make collider header-only, @pca006132 in #871
- Improve our CMake, @cjmayo in #880, #888, #899, #946, #948, #1002, #1029
- C bindings are required to build Python package, @jonathanhogg in #883
- Remove QuickHull dependency, @Kushal-Shah-03 (through [GSoC](https://summerofcode.withgoogle.com/)) in #881, #875, #893, #904, #908
- Add *.pc file for easier use in non-cmake environments, @hzeller in #901
- Enable MeshIO/MANIFOLD_EXPORT in flake, @reinux in #912
- Make cross_section an installable library, @hzeller in #915
- Fix `test-{cmake,pkgconfig}.sh` to create, not append, to test files, @hzeller in #919
- Use mxe to cross compile to windows, @pca006132 in #924
- Fix deployment, @elalish in #937
- Cleanup, @wtholliday in #954, #955, #956, #985
- Use nanobind builtin stubgen, @pca006132 in #949
- Format cmake files, @pca006132 in #975
- Remove CGAL comparisons, @elalish in #1009
- Fix atomic exchange template deduction, @pca006132 in #1035
- Remove OneDPL, @pca006132 in #1042
- Manifold CMake alias, @pca006132 in #1049
- Provide a numeric version number to compare against, @hzeller, @pca006132 in #1054, #1055

## Tests
- Fixed test flake, @cjmayo in #848
- Fix hull_test `isMeshConvex()` vertices check, @cjmayo in #898
- Use custom file format for polygon tests, @pca006132 in #913
- Define a test for simple offset booleans, @starseeker in #998

## Documentation
- Update README, @cjmayo, @elalish in #892, #920, #1015, #1025
- Implemented [typedoc documentation](https://manifoldcad.org/jsdocs/) for WASM bindings, @msantic in #907
- Doxygen updates, @elalish in #1014, #1020, #1043

## New Contributors
* @BenFrantzDale made their first contribution in #869
* @jonathanhogg made their first contribution in #883
* @Kushal-Shah-03 made their first contribution in #875
* @hzeller made their first contribution in #901
* @reinux made their first contribution in #912
* @dsafa made their first contribution in #914
* @msantic made their first contribution in #907
* @neilpa made their first contribution in #930
* @wtholliday made their first contribution in #954
* @NickUfer made their first contribution in #964
* @james-bern made their first contribution in #1034

**Full Changelog**: https://github.com/elalish/manifold/compare/v2.5.1...v3.0.0

### CODE REVIEW

**Comment by elalish** [comment]
I think we should probably update the README some more here, but I need to think about it a bit more. Suggestions welcome.

@pca006132 WDYT, are we ready for v3.0 release? Anything we should hold for?

**Comment by pca006132** [comment]
I think the only potential blocker is the C binding stuff, as that is a breaking change. I think we can just go ahead with the changes if no one opposes to it.

1. Some of the dependency description is not formatted correctly in the README (' vs \`):
   
   image

2. We are using nanobind instead of pybind11.
3. Should probably mention the dependency name instead of its name in Ubuntu ppa (e.g. not `libtbb-dev` but tbb).
4. Offline building: Missing `FETCHCONTENT_SOURCE_DIR_CLIPPER2`.
5. Can remove the remarks about Emscripten version. We are already using 3.1.61 in our CI.
6. Should probably remove the part about fuzzing support, as it is not working for now.
7. Can add a shell command about using of the formatting script, and maybe git precommit hook for it (we should probably use it ourselves...).
8. Windows shenanigans: Not sure if this is important now, considering we only have one main dll. Probably need someone more familiar with windows to decide. We can keep it for now.
9. I can probably find some time and write instructions for developing on nix.

**Comment by pca006132** [comment]
@SovereignShop btw is it possible for you to make the Clojure binding depends on the C binding alone? Also @geoffder.

**Comment by elalish** [comment]
Okay, SG - we'll hold this release for the C bindings update if you have time to take care of it. I'm not very comfortable with C myself. Meanwhile I'll update the README - thanks for the comments.

**Comment by geoffder** [comment]
> @SovereignShop btw is it possible for you to make the Clojure binding depends on the C binding alone? Also @geoffder. i.e. without the need for a fork. We can try to integrate the changes needed before we release v3.0.

Unfortunately my hiatus has meant I haven't found time to update my OCaml Manifold library in some time, but I already wasn't depending on a fork, just an unadulterated git submodule. If I'm understanding your question correctly.

**Comment by pca006132** [comment]
@geoffder yeah if you can use the C binding directly already, it is good.

@elalish I will try to find some time to do it, I am stretched really thin recently.

**Comment by elalish** [comment]
@pca006132 Thanks, but don't burn yourself out over these C bindings. We can put out v3.0 without it too if it's unreasonable in the near term. I don't have a good sense of how much work it will be.

**Comment by elalish** [comment]
One more question: should I remove the `deterministic` option for v3.0? I'm concerned it makes the library harder to test, and is it really deterministic even when true? If we remove it, which branch should we keep?

**Comment by pca006132** [comment]
1. Yeah, we can remove it. I think we can just keep the deterministic version, iirc it is fast enough. Not sure if it is fully deterministic, but ideally it should be.
2. I don't think C binding requires too much work. But it is still some work that I need to find time to do :)

**Comment by starseeker** [comment]
@elalish so does releasing 3.0 warrant another blog post? ;-)

**Comment by elalish** [comment]
> @elalish so does releasing 3.0 warrant another blog post? ;-)

Yeah - I should write some on the smoothing and SDF work I've done too. All in my copious spare time...

**Comment by elalish** [comment]
Okay, I've added some README cleanup and bumped the version to 3.0. I also went through our release checklist and though I'm not sure what change(s) was responsible, our WASM is now about twice as fast for me (running examples on ManifoldCAD.org), so that's a good sign. 

The only question now is whether we should wait for #1048 (or some subset of it) before cutting v3.0. @kintal - you have the strongest opinions here, so let me know. I'd like to get this out the door, but not at the cost of usability.

**Comment by hzeller** [comment]
I think it would be good if it was possible to query the manifold version in software, e.g. some macros to define `MANIFOLD_MAJOR`, `MANIFOLD_MINOR`  or other schemes to query the version, probably defined some header like `manifold/version.h` or similar. It should be macros so that it is possible in downstream applications to keep things compatible with `#ifdef`s.

Would probably good to have something like this starting with v3.0.

(context: I was just looking how easy it would be to get the version from Manifold to implement https://github.com/openscad/openscad/issues/5432 ... but it is not in any Manifold-provided header, and trying to get things from the build system such as cmake is sketchy at best).

**Comment by kintel** [comment]
+1: Compile-time version checking would be nice. It doesn't matter much as long as everyone is using manifold from git HEAD, but as we start seeing multiple deployed versions in the wild, we eventually have to make compile-time feature/version checks.

**Comment by kintel** [comment]
I'd say wait for #1048 - but thinking about it , it really doesn't matter too much - that doesn't change the API, so it could easily be made part of 3.0.1. Just beat the package managers to the punch by rolling out build system fixes fast :)

**Comment by pca006132** [comment]
> I'd say wait for #1048 - but thinking about it , it really doesn't matter too much - that doesn't change the API, so it could easily be made part of 3.0.1. Just beat the package managers to the punch by rolling out build system fixes fast :)

Not sure if that is a good idea. This will render our 3.0 release as something weird that distros should avoid...

**Comment by elalish** [comment]
Okay, now's the moment - are we ready to push v3.0? Speak now, or suffer the fate of a point release.

**Comment by pca006132** [comment]
I think it is ready.

**Comment by jonathanhogg** [comment]
Just wanted to note that there don't seem to be wheels being built for Python 3.13

**Comment by jonathanhogg** [comment]
@pca006132: Yeah, I think `cibuildwheel` picks up the supported versions from the tags in the `pyproject.toml` file and then builds a wheel for each one.

PyPA will let you add wheels to a release, but not change any of the original files. So it depends on your CI script as to whether it will barf on the existing ones or silently ignore the upload failures it gets.

I don't know if there's a way of marking a binary wheel as being compatible with more than one version…

Luckily the source build works now ;-)

**Comment by pca006132** [comment]
https://github.com/elalish/manifold/actions/runs/11906944291

It builds python 3.13 wheels, but the upload action is having issues. Maybe we should manually upload the missing binaries? Will have a look at how to do that.

**Comment by pca006132** [comment]
OK, I downloaded the artifacts and uploaded them manually.

**Comment by cartesian-theatrics** [comment]
Wow, this is a massively breaking release. Gonna take a long time to support. Is there a plan to stabalize a bit more moving forward?

**Pull request merged**
