### PR TITLE
[FIX] Packaged Split() output to Tuple

### PR DESCRIPTION
**Pull request by zalo**
This PR attempts to resolve https://github.com/elalish/manifold/issues/592 but is untested (due to Thrust related build issues on my end).

Hopefully Github Actions will vindicate me 🤞

### CODE REVIEW

**Comment by pca006132** [comment]
Thanks! Maybe you can add a python test example that uses `Split()` as well?

**Comment by zalo** [comment]
> Thanks! Maybe you can add a python test example that uses `Split()` as well?

Just added an example that should work.   On the current public Windows wheel, this:
```python
from manifold3d import Manifold
def run():
    a = Manifold.cube(1.0, 1.0, 1.0)
    b = Manifold.cube(1.0, 1.0, 1.0).rotate(45.0, 45.0, 45.0)
    return a.split(b)[0]
```

Yields:
```python
Traceback (most recent call last):
  File "c:\Repositories\manifold\bindings\python\examples\run_all.py", line 35, in <module>
    model = module.run()
  File "c:\Repositories\manifold\bindings\python\examples\split_cube.py", line 22, in run
    return a.split(b)[0]
TypeError: Unable to convert function return value to a Python type! The signature was
    split(self, arg: manifold3d.Manifold, /) -> std::pair<manifold::Manifold,manifold::Manifold>
```

Does the Github Action run `run_all.py`?

**Comment by pca006132** [comment]
> Does the Github Action run `run_all.py`?

yes it does

**Comment by elalish** [comment]
Excellent, thank you! We should probably put out a point release with this fix, but let's wait a couple days to see if any more bugs come in first.

**Pull request merged**
