### PR TITLE
Workflow builds

### PR DESCRIPTION
**Pull request by cartesian-theatrics**

### CODE REVIEW

**Comment by elalish** [comment]
A preview?

**Comment by geoffder** [comment]
Not sure why manifold would be moved into a "cpp" directory, with Java alongside it rather than putting java alongside the other bindings.

**Comment by cartesian-theatrics** [comment]
Sorry, I meant to open this against my fork!

> Not sure why manifold would be moved into a "cpp" directory, with Java alongside it rather than putting java alongside the other bindings.

The cpp code here is mostly intended to facilitate the java bindings by providing efficient mapping to c++ structures. Plus there a little extra functionality to support more openscad functionality. I wanted to keep all the changes under one directory so upkeep would be easier.

You know you have a great library when everyone and their mother wants to bind to it lol.

**Comment by hrgdavor** [comment]
>You know you have a great library when everyone and their mother wants to bind to it lol.

That is so true. I am personally impressed how fast this library became stable and useful.

**Pull request closed without merging**
